name: notes.whoisjason.me
services:
  notes:
    cpu_shares: 90
    command: []
    container_name: notes-whoisjason
    depends_on:
      pocketbase:
        condition: service_started
        required: true
    deploy:
      resources:
        limits:
          memory: 22957M
    entrypoint:
      - sh
      - -c
      - |
        echo "=== Notes Production Startup Log ==="
        echo "Node version: $(node --version)"
        echo "NPM version: $(npm --version)"
        echo "Operating system: $(uname -a)"
        echo ""

        echo "[STEP 1] Installing dependencies..."
        apk add --no-cache git openssh-client
        echo "Git installed: $(git --version)"
        echo ""

        echo "[STEP 2] Setting up workspace..."
        rm -rf /app/* /app/.[^.]* 2>/dev/null || true
        echo ""

        echo "[STEP 3] Cloning notes repository..."
        cd /tmp
        rm -rf notes 2>/dev/null || true
        git clone https://github.com/ljis120301/notes.git notes
        if [ $? -ne 0 ]; then
          echo "ERROR: Failed to clone notes repository"
          exit 1
        fi

        echo "Moving repository to /app..."
        cp -r /tmp/notes/. /app/
        cd /app
        echo "Notes repository cloned successfully"
        echo ""

        echo "[STEP 4] Verifying project structure..."
        if [ -f package.json ]; then
          echo "✓ package.json found"
        else
          echo "ERROR: package.json not found!"
          exit 1
        fi

        if [ -f next.config.ts ]; then
          echo "✓ next.config.ts found"
        else
          echo "✗ next.config.ts not found"
        fi

        if [ -d app ]; then
          echo "✓ app directory found"
        else
          echo "✗ app directory not found"
        fi

        if [ -d components ]; then
          echo "✓ components directory found"
        else
          echo "✗ components directory not found"
        fi
        echo ""

        echo "[STEP 5] Installing npm dependencies..."
        npm install --production=false
        if [ $? -ne 0 ]; then
          echo "ERROR: npm install failed"
          exit 1
        fi
        echo "Dependencies installed successfully"
        echo ""

        echo "[STEP 6] Building application for production..."
        npm run build
        if [ $? -ne 0 ]; then
          echo "ERROR: Production build failed"
          exit 1
        fi
        echo "Application built successfully"
        echo ""

        echo "[STEP 7] Starting production server..."
        echo "Starting Next.js in production mode on port 3003..."
        exec npm run start
    environment:
      - GIT_TERMINAL_PROMPT=0
      - NODE_ENV=production
      - PORT=3003
      - NEXT_PUBLIC_POCKETBASE_URL=https://pb2.whoisjason.me
    hostname: notes
    image: node:20-alpine
    labels:
      icon: https://www.vecteezy.com/vector-art/29722382-notes-icon-in-trendy-flat-style-isolated-on-white-background-notes-silhouette-symbol-for-your-website-design-logo-app-ui-vector-illustration-eps10
    ports:
      - target: 3003
        published: "3003"
        protocol: tcp
    restart: unless-stopped
    working_dir: /app
    x-casaos:
      architectures:
        - amd64
        - arm64
      category: Productivity
      description:
        en_us: A Next.js notes platform with PocketBase backend running in production mode.
          Automatically pulls the latest code from the notes GitHub repository and builds for
          optimized performance.
      developer: ljis120301
      icon: https://cdn.jsdelivr.net/gh/walkxcode/dashboard-icons/png/blog.png
      index: /
      main: notes
      port_map: "3003"
      scheme: http
      store_app_id: notes
      tagline:
        en_us: Notes - Production Next.js Notes Platform
      tips:
        en_us: The application will automatically pull the latest code from the notes
          GitHub repository and build for production on each container restart. Access the 
          notes at http://your-server-ip:3003. PocketBase admin interface is available at
          http://your-server-ip:6969/_/. Check container logs for build and startup
          information.
    volumes: []
    devices: []
    cap_add: []
    network_mode: bridge
    privileged: false
  pocketbase:
    cpu_shares: 90
    command: []
    container_name: pocketbase-notes
    deploy:
      resources:
        limits:
          memory: 22957M
    entrypoint:
      - sh
      - -c
      - >
        echo "=== PocketBase Startup Log ==="

        echo "Operating system: $(uname -a)"

        echo ""


        echo "[STEP 1] Installing dependencies..."

        apk add --no-cache git openssh-client

        echo "Git installed: $(git --version)"

        echo ""


        echo "[STEP 2] Setting up workspace..."

        rm -rf /app/* /app/.[^.]* 2>/dev/null || true

        echo ""


        echo "[STEP 3] Cloning notes repository..."

        cd /tmp

        rm -rf notes 2>/dev/null || true

        git clone https://github.com/ljis120301/notes.git notes

        if [ $? -ne 0 ]; then
          echo "ERROR: Failed to clone notes repository"
          exit 1
        fi


        echo "Moving repository to /app..."

        cp -r /tmp/notes/. /app/

        cd /app

        echo "Notes repository cloned successfully"

        echo ""


        echo "[STEP 4] Verifying PocketBase binary..."

        if [ -f ./pocketbase/pocketbase ]; then
          echo "✓ PocketBase binary found at /app/pocketbase/pocketbase"
          echo "PocketBase version: $(./pocketbase/pocketbase --version 2>/dev/null || echo 'Unable to determine version')"
        else
          echo "⚠️  PocketBase binary not found in repository, checking mounted volume..."
          
          if [ -f /pocketbase/pocketbase ]; then
            echo "✓ PocketBase binary found in mounted volume at /pocketbase/pocketbase"
            echo "PocketBase version: $(/pocketbase/pocketbase --version 2>/dev/null || echo 'Unable to determine version')"
            
            # Create symlink to make it available at expected location
            mkdir -p /app/pocketbase
            ln -sf /pocketbase/pocketbase /app/pocketbase/pocketbase
            echo "✓ Created symlink from /pocketbase/pocketbase to /app/pocketbase/pocketbase"
          else
            echo "ERROR: PocketBase binary not found in repository or mounted volume"
            echo "Current directory contents:"
            ls -la /app/
            if [ -d /pocketbase ]; then
              echo "Contents of /pocketbase:"
              ls -la /pocketbase/
            fi
            echo "Please ensure the PocketBase binary is available in the mounted volume at /pocketbase/pocketbase"
            exit 1
          fi
        fi

        echo ""


        echo "[STEP 5] Starting PocketBase server..."

        echo "Starting PocketBase on 0.0.0.0:6969..."

        exec ./pocketbase/pocketbase serve --http=0.0.0.0:6969
    environment:
      - GIT_TERMINAL_PROMPT=0
    hostname: pocketbase
    image: alpine:latest
    labels:
      icon: https://www.vecteezy.com/vector-art/29722382-notes-icon-in-trendy-flat-style-isolated-on-white-background-notes-silhouette-symbol-for-your-website-design-logo-app-ui-vector-illustration-eps10
    ports:
      - target: 6969
        published: "6969"
        protocol: tcp
    restart: unless-stopped
    volumes:
      - /home/jason/pocketbase-notes/pocketbase:/pocketbase
    working_dir: /app
    x-casaos:
      architectures:
        - amd64
        - arm64
      category: Database
      description:
        en_us: PocketBase backend database for the Notes application. Provides API
          endpoints and admin interface.
      developer: ljis120301
      icon: https://cdn.jsdelivr.net/gh/walkxcode/dashboard-icons/png/database.png
      index: /_/
      main: pocketbase
      port_map: "6969"
      scheme: http
      store_app_id: pocketbase
      tagline:
        en_us: PocketBase - Backend Database
      tips:
        en_us: PocketBase admin interface is available at http://your-server-ip:6969/_/.
          Database files are persisted to /home/jason/pocketbase-notes/pocketbase on the host
          system.
    devices: []
    cap_add: []
    network_mode: bridge
    privileged: false
x-casaos:
  author: self
  category: self
  hostname: ""
  icon: https://www.vecteezy.com/vector-art/29722382-notes-icon-in-trendy-flat-style-isolated-on-white-background-notes-silhouette-symbol-for-your-website-design-logo-app-ui-vector-illustration-eps10
  index: /
  is_uncontrolled: false
  port_map: ""
  scheme: http
  store_app_id: notes.whoisjason.me
  title:
    custom: ""
    en_us: notes
